### ISSUE TITLE
can you make a explain for isShared and maxWaiting in readme 

### ISSUE THREAD

**Issue by fangjj** [nlhuykhang/meteor-publish-join#14]
i'm confused, can you make a explain for isShared and maxWaiting in readme ?

**Comment by SimonSimCity** [comment]
The `isShared` property was requested by me in https://github.com/nlhuykhang/meteor-publish-join/issues/2 which you can take a look at to understand the purpose of it.

`maxWaiting` is a bit more complicated ...

The `join` will re-run every `interval`-time excepted for if the last publish is still ongoing. The option `maxWaiting` is about to consider how long the plugin should wait until it considers the last publish as `stale` and runs another one - if I interpret the code right.

Since the codebase isn't really big, I also encourage you to read through it and understand what's actually going on here under the hood.

**Comment by fangjj** [comment]
nice, thank for your explains. it's very clear and helpful.
