### ISSUE TITLE
Is the result shared if many clients subscribe?

### ISSUE THREAD

**Issue by SimonSimCity** [nlhuykhang/meteor-publish-join#2]
Just a question to get this right the first time:

I'm working on a tool, where we'll have to publish a lot of these publications, often not related to a user. We'll also have quite some clients that will subscribe on those.

Will the agregation/query be re-run for every client, subscribing on this publication in the given interval, or is there a possibility, where I can save the value globally, so the next client, subscribing to it, will get the already computed one if it isn't the right time to re-run the computation?

**Comment by nlhuykhang** [comment]
Good point, I never thought about this before. Right now, this module doesn't have any kind of caching for similar queries so query will be re-run for every client. 

I think I would implement this feature this weekend. Will open for any suggestion you have.

**Comment by SimonSimCity** [comment]
Maybe this helps:

This plugin has a way to do this: https://atmospherejs.com/natestrauser/publish-performant-counts
But I don't know if a caching approach would be better, because - using caching - you could do even better - namely - just generating the values if needed, but share them with a key. The programmer than has to make sure this key is unique (maybe a stringyfied-version of the parameters he gives to the method ...)

**Comment by nlhuykhang** [comment]
hey,
I already worked on this feature, and published it to npm under tag `share-join`. You can install it with: `npm install --save meteor-publish-join@share-join`.

I do not want to publish it as the latest version because the code base is now relatively bigger than before, and is easier to break something. But no tests have been written to make sure everything work. I plan to work on implementing automation tests first. Then I can publish new version confidently.

The new API add one more option `isShared` to `JoinServer.publish` function. To make a join shared across many subscriber, simply pass `isShared: true`:

```
  JoinServer.publish({
    context: this,
    name: 'numComments',
    interval: 1000,
    doJoin() {
      // ...
    },
    isShared: true,
  });
```

**Comment by SimonSimCity** [comment]
I've just seen, you've published a public version with this feature. I sadly haven't had time to check it out in the meanwhile, since we're quite close to the deadline of a first version, where this isn't considered a must-have.

Please close this issue if you consider this feature to be stable. I saw you've also added quite some tests 😉 ...

**Comment by SimonSimCity** [comment]
Tested, works.

Thanks for your time on this one!
